### ISSUE TITLE
Update docs

### ISSUE THREAD

**Issue by davidsalamon** [cloudstorm/cloudstorm#32]
- [x] Check links / anchors (search phrase: `](#`)
- [x] wiki with attribute and event tables
see https://github.com/angular-ui/ui-select/wiki/ui-select
- [x] Files distributed in doc folder

**Comment by bence-nagy** [comment]
See also: 
https://github.com/bower/spec/blob/master/json.md

(Linked source in doc.)
